language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install pytest pytest-cov
  - pip install coveralls pytest-pep8
script:
  - py.test test/*.py --doctest-modules --pep8 test -v --cov test --cov-report term-missing
after_success:
  - coveralls